baseURL = "/"
languageCode = "en-us"
theme = "poison"
paginate = 10
pluralizelisttitles = false # removes the automatically appended "s" on sidebar entries

# NOTE: If using Disqus as commenting engine, uncomment and configure this line
# disqusShortname = "yourDisqusShortname"

[params]
brand = "Jordan"                                                                                         # name of your site - appears in the sidebar
remote_brand_image = 'https://jt-public-bucket.s3.us-west-2.amazonaws.com/IMG_1888.jpg?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEDMaCXVzLWVhc3QtMSJGMEQCIAMXTjWlAslILLvpAV21MZREDqwFYaHr3ZXOONRaHfpKAiAPelg74169HaBnVIWHzcvnOGbOHCaKzHhZGwFFP7h2WyrkAgh8EAQaDDk5OTQ1MDI2OTMzOCIMA/C3VmhYHy0SQ5JqKsECwGrrGFPoHLyS864O+UckUkBf7/pfh6R6+aVnptxqsixWDGKvkq8fJyJCeRxvRTzvklNwQw+GP0Ggg4oBrYoRVFyjCLvTSd1DfC0+1hO2ke02z/6FBsfs0BG5WEX6P7SmVf7YqPzMpAS1WTZQxrrIaOGAWx5pQZSf/R6Cs8qrlB/2isSGyqsC9NQS/Vf08HUwJDAniE2657jSChuJJqUyZFqBZx/ROtILweoas7v+Kjxg8JM4G1HNFfIgTJZ57voYxbZcFOtIAK7yDR5x4HMmADYbOWvY5sRCcUjW/F4p0h9u49AN8vtq1maXjvZBAHRuqLppPxAYBTKxZuEam9VCH/h3eVYUGqUWMBiGvd5lVm0lyYYHxzopKRgHY9grwGI4XD16INClvvvhK3ZUGzebu1VBTDjsa64x7cBH+yQpmoQFMMH2n7EGOrQCHcQf4FlicPP35YH2jpuYGME8uPaTTWBCZAhjq44rXwwmQJuUGL/gqTdZPcQsd6LB02IJiXCBNG3eE3yo34iG0GfsR5bPH7nVdJ8+lUw08rp+c0K8saVRojPBO9oI5ihXkm9N4qAlybeQ1I6KUOhhCa3ybG4ugQwy73JkXirvrSmJ5I2GqbPelQ7T5h6hJAiPE34iAech0iLrlclVNQCGvFV9qKPo5VcBUTidy2OJLyUtGknD4YSWBzeNcw8MxJHmqcrSt5+Mv7XEXodpsL2k0dOJwSEGc/B/gF6vnO8gAqGGOOM1MzGtKAx7OvgM9ON3rXBwSZD71f/DZz20EmZWI2KPOE5hh8fjREEexJiEIcyEnR0Itxtor96Znt/BnNupMoagF9VLkCH6ensPU+fqToIVzCQ%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240423T182331Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIA6RM7A22NG7PSE2AD/20240423/us-west-2/s3/aws4_request&X-Amz-Signature=a31c80515593f9e2173bd477953c0bf5d819b84066fb313e5624f54661b38727'.                             # path to a remote file
description = "just another software dude -  <a href='https://www.linkedin.com/in/justjordant/'>@Jt</a>" # Used as default meta description if not specified in front matter# brand_image = "/images/ME.jpeg"            # path to the image shown in the sidebar
dark_mode = true                                                                                         # optional - defaults to false
favicon = "favicon.png"                                                                                  # path to favicon (defaults to favicon.png)

front_page_content = [
	"posts",
] # Equivalent to the default value, add page bundle names to include them on the front page.

# MENU PLACEHOLDER
# Menu dict keys:
# Name:         The name to display on the menu.
# URL:          The directory relative to the content directory.
# HasChildren:  If the directory's files should be listed.  Default is true.
# Limit:        If the files should be listed, how many should be shown.
menu = [
	{ Name = "About", URL = "/about/", HasChildren = false },
	{ Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 2 },
	{ Name = "Projects", URL = "/projects/", Pre = "Recent", HasChildren = true, Limit = 2 },
	{ Name = "Tags", URL = "/tags/", HasChildren = false },
]

# Links to your socials.  Comment or delete any you don't need/use. 
# discord_url = "https://discord.com"
email_url = "mailto://jordantay9014@gmail.com"
# # facebook_url = "https://facebook.com"
# flickr_url = "https://flickr.com"
github_url = "https://github.com/justjordant"
# gitlab_url = "https://gitlab.com"
# instagram_url = "https://instagram.com"
linkedin_url = "https://www.linkedin.com/in/justjordant/"
# mastodon_url = "https://mastodon.social"
# matrix_url = "https://matrix.org"
# telegram_url = "https://telegram.org"
# tryhackme_url = "https://tryhackme.com"
twitter_url = "https://twitter.com/Just_Jordan_T"
# xmpp_url = "https://xmpp.org"
youtube_url = "https://www.youtube.com/channel/UCWMddXhNGWkzBYYS9cv-7Qg"

# NOTE: If you don't want to use RSS, comment or delete the following lines
# Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
rss_icon = true
# Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
rss_section = "posts"

# Hex colors for your sidebar.
moon_sun_background_color = "#515151" # default is #515151
moon_sun_color = "#FFF"               # default is #FFF
sidebar_a_color = "#FFF"              # default is #FFF
sidebar_bg_color = "#202020"          # default is #202020
sidebar_h1_color = "#FFF"             # default is #FFF
sidebar_img_border_color = "#515151"  # default is #515151
sidebar_p_color = "#909090"           # default is #909090
sidebar_socials_color = "#FFF"        # default is #FFF

# Hex colors for your content in light mode.
code_color = "#000"                     # default is #000
code_background_color = "#E5E5E5"       # default is #E5E5E5
code_block_color = "#FFF"               # default is #FFF
code_block_background_color = "#272822" # default is #272822
content_bg_color = "#FAF9F6"            # default is #FAF9F6
date_color = "#515151"                  # default is #515151
link_color = "#268BD2"                  # default is #268BD2
list_color = "#5A5A5A"                  # default is #5A5A5A
post_title_color = "#303030"            # default is #303030
table_border_color = "#E5E5E5"          # default is #E5E5E5
table_stripe_color = "#F9F9F9"          # default is #F9F9F9
text_color = "#222"                     # default is #222

# Hex colors for your content in dark mode
code_color_dark = "#FFF"                     # default is #FFF
code_background_color_dark = "#515151"       # default is #515151
code_block_color_dark = "#FFF"               # default is #FFF
code_block_background_color_dark = "#272822" # default is #272822
content_bg_color_dark = "#121212"            # default is #121212
date_color_dark = "#9A9A9A"                  # default is #9A9A9A
link_color_dark = "#268BD2"                  # default is #268BD2
list_color_dark = "#9D9D9D"                  # default is #9D9D9D
post_title_color_dark = "#DBE2E9"            # default is #DBE2E9
table_border_color_dark = "#515151"          # default is #515151
table_stripe_color_dark = "#202020"          # default is #202020
text_color_dark = "#EEE"                     # default is #EEE

# NOTE: If using Remark42 as commenting engine, uncomment and configure these lines
# remark42 = true
# remark42_host = "https://yourhost.com"
# remark42_site_id = "your_site_id"

# NOTE: The following three params are optional and are used to create meta tags + enhance SEO.
# og_image = ""                       # path to social icon - front matter: image takes precedent, then og_image, then brand_url
# this is also used in the schema output as well. Image is resized to max 1200x630
# For this to work though og_image and brand_url must be a path inside the assets directory
# e.g. /assets/images/site/og-image.png becomes images/site/og-image.png
# publisher_icon = ""                 # path to publisher icon - defaults to favicon, used in schema

[params.meta]
favicon = true

[taxonomies]
series = 'series'
tags = 'tags'
